---
- hosts: all
  become: yes
  tasks:
    - name: disable ctrl-alt-del.target
      systemd:
        name: ctrl-alt-del.target
        masked: yes
    - name: copy system.conf
      copy:
        src: system.conf
        dest: /etc/systemd/system.conf
        mode: 0644
        owner: root
        group: root
