---
- hosts: all
  become: yes
  tasks:
    - name: diff file
      stat:
        path: "/tmp/test1/test1_1/test1_1_1"
        state: directory
        owner: "root"
        group: "root"
        mode: "775"
        recurse: yes
