---
- hosts: all
  become: yes
  tasks:
    - name: Create hello-world
      community.general.docker_container:
        name: hello
        image: hello-world
        auto_remove: yes
        container_default_behavior: compatibility
      vars:
        ansible_python_interpreter: /root/.pyenv/versions/3.8.1/bin/python
