---
- hosts: all
  become: yes
  tasks:
    - name: Stop nginx
      community.general.docker_container:
        name: nginx
        image: nginx:latest
        state: stopped
        container_default_behavior: compatibility
      vars:
        ansible_python_interpreter: /root/.pyenv/versions/3.8.1/bin/python
